#!/usr/bin/env python3
"""
ROM converter for Space Invaders (Midway, 1978)
Converts invaders ROM files to C header files for Galagino

Space Invaders ROM set:
  invaders.h  (2KB, 0x0000-0x07FF)
  invaders.g  (2KB, 0x0800-0x0FFF)
  invaders.f  (2KB, 0x1000-0x17FF)
  invaders.e  (2KB, 0x1800-0x1FFF)

Total: 8KB CPU ROM
No separate tile/sprite ROMs - uses bitmap framebuffer

Usage:
  python romconv_spaceinvaders.py

  Place ROM files in ../roms/ directory first.
"""

import os
import sys

ROM_SRC = os.path.normpath(os.path.join("..", "roms"))
OUT_DIR = os.path.normpath(os.path.join("..", "..", "source", "src", "machines", "spaceinvaders"))

# ROM file names for Space Invaders
ROM_FILES = [
    ("invaders.h", 0x0800),  # 2KB at 0x0000
    ("invaders.g", 0x0800),  # 2KB at 0x0800
    ("invaders.f", 0x0800),  # 2KB at 0x1000
    ("invaders.e", 0x0800),  # 2KB at 0x1800
]

def load_file(name):
    """Load a ROM file from the source directory"""
    path = os.path.join(ROM_SRC, name)
    if not os.path.exists(path):
        # Try case-insensitive match
        for alt in [name.lower(), name.upper()]:
            alt_path = os.path.join(ROM_SRC, alt)
            if os.path.exists(alt_path):
                path = alt_path
                break
    if not os.path.exists(path):
        print(f"ERROR: File '{name}' not found in {os.path.abspath(ROM_SRC)}")
        return None
    with open(path, "rb") as f:
        return bytearray(f.read())

def write_header(filename, array_name, data, description=""):
    """Write a C header file with PROGMEM array"""
    filepath = os.path.join(OUT_DIR, filename)
    with open(filepath, "w") as f:
        f.write(f"// {description}\n")
        f.write(f"// Auto-generated by romconv_spaceinvaders.py - DO NOT EDIT\n\n")
        f.write(f"#ifndef _{array_name}_h_\n")
        f.write(f"#define _{array_name}_h_\n\n")
        f.write(f"const unsigned char {array_name}[{len(data)}] = {{\n")

        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(data):
                hex_str += ","
            f.write(f"  {hex_str}\n")

        f.write(f"}};\n\n")
        f.write(f"#endif\n")

    print(f"  Written: {filepath} ({len(data)} bytes)")

def main():
    # Create output directory if needed
    os.makedirs(OUT_DIR, exist_ok=True)

    print(f"Loading ROMs from: {os.path.abspath(ROM_SRC)}")
    print(f"Output directory: {os.path.abspath(OUT_DIR)}")

    # Load all ROM files
    rom_data = bytearray()
    
    for rom_name, expected_size in ROM_FILES:
        data = load_file(rom_name)
        if data is None:
            print(f"ERROR: Failed to load {rom_name}")
            sys.exit(1)
        
        if len(data) != expected_size:
            print(f"WARNING: {rom_name} is {len(data)} bytes, expected {expected_size}")
        
        rom_data.extend(data[:expected_size])
        print(f"  Loaded: {rom_name} ({len(data)} bytes)")

    print(f"\nTotal ROM: {len(rom_data)} bytes")

    if len(rom_data) != 8192:
        print(f"ERROR: Expected 8192 bytes, got {len(rom_data)}")
        sys.exit(1)

    # Write ROM header
    write_header(
        "spaceinvaders_rom.h",
        "spaceinvaders_rom",
        rom_data,
        "Space Invaders CPU ROM (8KB: invaders.h + .g + .f + .e)"
    )

    print("\nDone! ROM converted successfully.")
    print("Space Invaders uses bitmap framebuffer - no tilemap/spritemap needed.")

if __name__ == "__main__":
    main()